### ISSUE TITLE
Crash when releasing video record button

### ISSUE THREAD

**Issue by aforcier** [Automattic/stories-android#121]
I get a crash when quickly recording video.

Steps:
1. Enter capture mode
2. Press and hold the capture button to start a video recording
3. Very quickly let go of the capture button to end the recording

```
2019-09-12 18:04:49.105 11476-11490/? E/AndroidRuntime: FATAL EXCEPTION: CameraX-
    Process: com.automattic.portkey, PID: 11476
    java.lang.IllegalArgumentException: Surface was abandoned
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:84)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:260)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:145)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:508)
        at androidx.camera.camera2.impl.CaptureSession.open(CaptureSession.java:285)
        at androidx.camera.camera2.impl.Camera.openCaptureSession(Camera.java:680)
        at androidx.camera.camera2.impl.Camera.onUseCaseReset(Camera.java:415)
        at androidx.camera.camera2.impl.Camera$9.run(Camera.java:402)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
        at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:606)
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:82)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:260) 
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:145) 
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:508) 
        at androidx.camera.camera2.impl.CaptureSession.open(CaptureSession.java:285) 
        at androidx.camera.camera2.impl.Camera.openCaptureSession(Camera.java:680) 
        at androidx.camera.camera2.impl.Camera.onUseCaseReset(Camera.java:415) 
        at androidx.camera.camera2.impl.Camera$9.run(Camera.java:402) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
```

GM demo, Pixel 3, Android 9

**Comment by aforcier** [comment]
Couldn't reproduce this anymore, just going to close it.
