### ISSUE TITLE
Crash when tapping on Stickers button rapidly twice

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#201]
On Samsung J2:

```
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.automattic.portkey, PID: 9542
    java.lang.IllegalStateException: Fragment already added: EmojiPickerFragment{41f9978 (e311c528-b95c-4aaa-8270-a6348ffa0529)}
        at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1379)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:399)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
D/io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
```

Steps to repro:
1. open the app
2. take a picture
3. tap on the Stickers button
4. tap again on the same button very quickly

**Comment by mzorz** [comment]
Duplicate of #455, closed in #456
